# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Halpradio < Formula
  desc "LazyVim-inspired Terminal Internet Radio Streamer"
  homepage "https://github.com/halpworld/halpradio"
  version "0.0.4"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.4/halpradio_0.0.4_darwin_amd64.tar.gz"
      sha256 "aff54a3544e0ff3f0ca97389aa8d436394409dfa96250953746ed627f08c0eed"

      define_method(:install) do
        bin.install "halpradio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.4/halpradio_0.0.4_darwin_arm64.tar.gz"
      sha256 "49ae6cf021886382ca0cb627ab0ad6dffe47b3866382217fb00da3cf5537ad94"

      define_method(:install) do
        bin.install "halpradio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.4/halpradio_0.0.4_linux_amd64.tar.gz"
      sha256 "474f4a981b542981f7defac94f6288585d4a61998335d4063856e60b763b8768"
      define_method(:install) do
        bin.install "halpradio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.4/halpradio_0.0.4_linux_arm64.tar.gz"
      sha256 "7542c90702e1337236cc5deaca037dc7b5cb2c0f12ee49b4ae935583e729824f"
      define_method(:install) do
        bin.install "halpradio"
      end
    end
  end

  test do
    assert_match "halpradio", shell_output("#{bin}/halpradio -version")
  end
end
