# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Halpradio < Formula
  desc "LazyVim-inspired Terminal Internet Radio Streamer"
  homepage "https://github.com/halpworld/halpradio"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.3/halpradio_0.0.3_darwin_amd64.tar.gz"
      sha256 "196c9cfd92c7608187d57d6ff818c78ad3292abe079db2f9cb5c0c95458e6624"

      define_method(:install) do
        bin.install "halpradio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.3/halpradio_0.0.3_darwin_arm64.tar.gz"
      sha256 "05ad5683903efb376b7b067a7cbf6d88d35b86a49246d958b402a81094b301ec"

      define_method(:install) do
        bin.install "halpradio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.3/halpradio_0.0.3_linux_amd64.tar.gz"
      sha256 "6169a1eefa28b9e8c2a08dfa0a8bb443cd5e443153615a41c9cce7a0cc62b058"
      define_method(:install) do
        bin.install "halpradio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.3/halpradio_0.0.3_linux_arm64.tar.gz"
      sha256 "6a0e11b5b6d99bf08a8c12acca7dba1997e2a92fe78001ed8b19c4d6f74a59df"
      define_method(:install) do
        bin.install "halpradio"
      end
    end
  end

  test do
    assert_match "halpradio", shell_output("#{bin}/halpradio -version")
  end
end
