# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Halpradio < Formula
  desc "LazyVim-inspired Terminal Internet Radio Streamer"
  homepage "https://github.com/halpworld/halpradio"
  version "0.5.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/halpworld/halpradio/releases/download/v0.5.0/halpradio_0.5.0_darwin_amd64.tar.gz"
      sha256 "45d0bbaa47412c3e8847e25f875a62df9d6349a4b21c9c605624645c8359fe55"

      define_method(:install) do
        bin.install "halpradio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/halpworld/halpradio/releases/download/v0.5.0/halpradio_0.5.0_darwin_arm64.tar.gz"
      sha256 "0212ea9e0b37c85c00de078f44cfdb4a3120417930e5b78af83ae37b58388710"

      define_method(:install) do
        bin.install "halpradio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/halpworld/halpradio/releases/download/v0.5.0/halpradio_0.5.0_linux_amd64.tar.gz"
      sha256 "e9a1021d94a34910c91c35b19525f1a54d1e02422c216adb7199dc2e32470493"
      define_method(:install) do
        bin.install "halpradio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/halpworld/halpradio/releases/download/v0.5.0/halpradio_0.5.0_linux_arm64.tar.gz"
      sha256 "ee9f9486558a852e1f1db07feb2b96b52dbf880c8e4041716cbf6ad063fe3b79"
      define_method(:install) do
        bin.install "halpradio"
      end
    end
  end

  test do
    assert_match "halpradio", shell_output("#{bin}/halpradio -version")
  end
end
