# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Halpradio < Formula
  desc "LazyVim-inspired Terminal Internet Radio Streamer"
  homepage "https://github.com/halpworld/halpradio"
  version "0.0.6"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.6/halpradio_0.0.6_darwin_amd64.tar.gz"
      sha256 "25f71feab46548273b4795b6905305da0f4bd7cd57e3c67291ea63d70d061f5d"

      define_method(:install) do
        bin.install "halpradio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.6/halpradio_0.0.6_darwin_arm64.tar.gz"
      sha256 "a9003e7656418b22a5a8885001c69c072750829630bb3b9b455425364543dd76"

      define_method(:install) do
        bin.install "halpradio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.6/halpradio_0.0.6_linux_amd64.tar.gz"
      sha256 "a5dc868632c516bf5791fb29cc2de74b7fbf04129726bdda983032cf3305281f"
      define_method(:install) do
        bin.install "halpradio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/halpworld/halpradio/releases/download/v0.0.6/halpradio_0.0.6_linux_arm64.tar.gz"
      sha256 "6eaa2757712d4551597569f63140ef15559efcad6bb56cbbf8e81d2eef7f4373"
      define_method(:install) do
        bin.install "halpradio"
      end
    end
  end

  test do
    assert_match "halpradio", shell_output("#{bin}/halpradio -version")
  end
end
